import os

##########################################################################
# Setup builders and environment

# We might be executed by the SConstuct above as a SConscript, so we
# need to force current directory on our custom builder
mpostBuilder = Builder(
    action='mpost ${SOURCE.file}',
    src_suffix='.mp',
    chdir=1
)

env = Environment(
    ENV      = os.environ,
    BUILDERS = { 'mpost': mpostBuilder },
)

##########################################################################
# Add builders and dependecies to environment

mp = env.mpost(
    target = ("class_diagram.1",),
    source = "class_diagram.mp"
)

pdf = env.PDF(
    target = "class_diagram.pdf",
    source = "class_diagram.tex"
)

Depends(pdf, mp)
